version: '2.4'
services:
  mysql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure:5
    ports:
      - '3306:3306'
    environment:
      # - MYSQL_ROOT_PASSWORD=test
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=SCORE
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure:5
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=mysql-db
    depends_on:
      - mysql-db
volumes:
  mysql-data: